#################################
# Mozilla Security/Server Side TLS Recommendation
# https://wiki.mozilla.org/Security/Server_Side_TLS
#--------------------------------
# How to use tls options on a router.
# Lables:
#traefik.routers.foo.tls.options=modern
#--------------------------------
# YML:
#http:
#  routers;
#    foo:
#      tls:
#        options: modern

tls:

  options:

    #################################
    # Modern Compatibility | Modern only
    # -------------------------------
    # TLS 1.3
    # -------------------------------
    # For services with clients that support TLS 1.3 and don't need backward compatibility,
    # the modern configuration provides an extremely high level of security.
    modern:
      minVersion: VersionTLS13
      sniStrict: true
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - X25519
        - prime256v1
        - secp384r1

    #################################
    # Modern Compatibility | Recommended
    # -------------------------------
    # TLS 1.3 | TLS 1.2
    # -------------------------------
    # For services that don't need compatibility with legacy clients such as Windows XP or old versions of OpenSSL.
    # This is the recommended configuration for the vast majority of services,
    # as it is highly secure and compatible with nearly every client released in the last five (or more) years.
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        # TLS 1.3
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        # TLS 1.2
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
        - ECDHE-ECDSA-CHACHA20-POLY1305
        - ECDHE-RSA-CHACHA20-POLY1305
        - DHE-RSA-AES128-GCM-SHA256
        - DHE-RSA-AES256-GCM-SHA384
        - DHE-RSA-CHACHA20-POLY1305
      curvePreferences:
        - X25519
        - prime256v1
        - secp384r1

    #################################
    # Legacy Compatibility | Not recommended
    # -------------------------------
    # TLS 1.3 | TLS 1.2 | TLS 1.1 | TLS 1.0
    # -------------------------------
    # This configuration is compatible with a number of very old clients,
    # and should be used only as a last resort.
    legacy:
      cipherSuites:
        # TLS 1.3
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        # TLS 1.2
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
        - ECDHE-ECDSA-CHACHA20-POLY1305
        - ECDHE-RSA-CHACHA20-POLY1305
        - DHE-RSA-AES128-GCM-SHA256
        - DHE-RSA-AES256-GCM-SHA384
        - DHE-RSA-CHACHA20-POLY1305
        - ECDHE-ECDSA-AES128-SHA256
        - ECDHE-RSA-AES128-SHA256
        - ECDHE-ECDSA-AES128-SHA
        - ECDHE-RSA-AES128-SHA
        - ECDHE-ECDSA-AES256-SHA384
        - ECDHE-RSA-AES256-SHA384
        - ECDHE-ECDSA-AES256-SHA
        - ECDHE-RSA-AES256-SHA
        - DHE-RSA-AES128-SHA256
        - DHE-RSA-AES256-SHA256
        - AES128-GCM-SHA256
        - AES256-GCM-SHA384
        - AES128-SHA256
        - AES256-SHA256
        - AES128-SHA
        - AES256-SHA
        - DES-CBC3-SHA
      curvePreferences:
        - X25519
        - prime256v1
        - secp384r1